window.VOICERA_CONFIG = {
  DG_KEY: 'YOUR_DEEPGRAM_KEY_HERE',
  SB_URL: 'YOUR_SUPABASE_URL_HERE',
  SB_KEY: 'YOUR_SUPABASE_ANON_KEY_HERE',
  FUNC_URL: 'YOUR_SUPABASE_FUNCTION_URL_HERE',
  FUNC_KEY: 'YOUR_SUPABASE_FUNCTION_KEY_HERE',
  SIMLI_API_KEY: 'YOUR_SIMLI_API_KEY_HERE',
  SIMLI_FACE_ID: 'YOUR_SIMLI_FACE_ID_HERE'
};
